### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by hahmyg** [swabhs/open-sesame#10]
When I test the trained argument identification model using 
` python segrnn-argid.py`

It returns three types of F1 scores:
wf1, uf1, and lf1

I cannot find a documentation for each evaluation metric.
Could you explain about those?

And, my another question is, is it evaluated by 'Gold Frames'? or 'Predicted Frames'?
if it is gold frames, How can I evaluate the end-to-end performance which is shown in Table 5 in your paper?

**Comment by swabhs** [comment]
I will add this to the documentation shortly. But here are your answers:

- u-f1  corresponds to unlabeled F1 which just checks if the argument spans are correct, irrespective of the role labels (frame elements).

- w-f1 corresponds to a word-level or token-level F1, which evaluates each argument token as if it was an independent argument.

- l-f1 corresponds to labeled F1, which is the metric reported officially in all publications as well as the Semeval task for FrameNet. 

The evaluation of arg-ID is with respect to the frames provided in the CoNLL file you are using for evaluation. That is, if the file contains gold frames in the frames column, the evaluation is with respect to gold frames, and so on. Mind you that this is only arg-id evaluation. For full semantic parse evaluation (frameid + argid), shown on the right column of Table 3 in the paper, I used the generated `.frame.elements` file and evaluated using this script - https://github.com/Noahs-ARK/semafor/blob/develop/scripts/scoring/runTestWithGoldTargets.sh

I will also try to add this evaluation to the codebase.
