### ISSUE TITLE
Using evaluation.py

### ISSUE THREAD

**Issue by GMarzinotto** [swabhs/open-sesame#11]
Hello,

Thank you very much for this contribution.
I would like to test open-sesame in new available FrameNet corpus.

I'm at the evaluation step
But I'm having a hard time using the evaluation.py script 
I see that it takes as input a file as the ones auto-generated in 
"./data/neural/fn1.6/fn1.6.test.syntaxnet.conll"

but it fails while loading the default TEST_FILE
I get the following stack trace

> File "evaluation.py", line 216, in <module>
>     goldexamples, _, _ = read_conll(goldfile)
>     File "/FRAME_PARSERS/open-sesame/src/dataio.py", line 38, in read_conll
>     e = CoNLL09Example(sentence, elements)
>     File "/FRAME_PARSERS/open-sesame/src/conll09.py", line 120, in __init__
>     if FEDICT.getid(NOTANFE) in self.invertedfes:
>     File "/FRAME_PARSERS/open-sesame/src/housekeeping.py", line 52, in getid
>     raise Exception("not in dictionary, but can be added", id)
> Exception: ('not in dictionary, but can be added', <built-in function id>)

Any ideas on how to fix this issue?
Kind regards,
Gabriel M

**Comment by swabhs** [comment]
Hi Gabriel,

Looks like there might be a difference in the data format of the file. The 15th column of the CoNLL file used must be in the BIO format for arguments. You're getting this error probably because you do not have "O" tags in the file you are using. Can you check? And if not, can you copy-paste one sentence in CoNLL format here?

Best,
Swabha

**Comment by GMarzinotto** [comment]
I don't think that's the case
Here is the first sentence of the file: data/neural/fn1.6/fn1.6.test.syntaxnet.conll
which was generated automatically using the provided preprocess.py script

> 1	Some	_	Some	dt	DT	0	_	_	_	_	_	_	_	O
> 2	of	_	of	in	IN	0	_	_	_	_	_	_	_	O
> 3	the	_	the	dt	DT	0	_	_	_	_	_	_	_	O
> 4	strongest	_	strongest	jjs	JJS	0	_	_	_	_	_	strong.a	Exertive_force	O
> 5	critics	_	critic	nns	NNS	0	_	_	_	_	_	_	_	B-Entity
> 6	of	_	of	in	IN	0	_	_	_	_	_	_	_	I-Entity
> 7	our	_	our	PP$	PRP$	0	_	_	_	_	_	_	_	I-Entity
> 8	welfare	_	welfare	nn	NN	0	_	_	_	_	_	_	_	I-Entity
> 9	system	_	system	nn	NN	0	_	_	_	_	_	_	_	I-Entity
> 10	are	_	be	vbp	VBP	0	_	_	_	_	_	_	_	O
> 11	the	_	the	dt	DT	0	_	_	_	_	_	_	_	O
> 12	people	_	people	nns	NNS	0	_	_	_	_	_	_	_	O
> 13	who	_	who	wp	WP	0	_	_	_	_	_	_	_	O
> 14	have	_	have	VHP	VBP	0	_	_	_	_	_	_	_	O
> 15	become	_	become	VVN	VBN	0	_	_	_	_	_	_	_	O
> 16	dependent	_	dependent	jj	JJ	0	_	_	_	_	_	_	_	O
> 17	on	_	on	in	IN	0	_	_	_	_	_	_	_	O
> 18	it	_	it	PP	PRP	0	_	_	_	_	_	_	_	O
> 19	.	_	.	sent	.	0	_	_	_	_	_	_	_	O


When I evaluate the gold file data/neural/fn1.6/fn1.6.test.syntaxnet.conll against himself
I would expect to get 100% performance but instead I get the error described above.

Should I try 1.5 and not 1.6?
It seems to me that my FE dictionary does not contain the Frames that I query:
But I'm having trouble understanding where 'FEDICT' gets initialized 


Thank you very much

**Comment by swabhs** [comment]
I have not seen this problem on 1.5, so you might want to try that, or 1.7.  It looks like some frame-element is missing in the original mapping, I'm trying to reproduce the error so I can add a fix. Thanks for your patience!

**Comment by GMarzinotto** [comment]
Thank you very much, I have tested with FrameNet 1.5, 1.6 and 1.7
and none of them worked in my compute. 
I'll try to give more details of my setup so the issue can be reproduced.

`ls open-sesame`  gives
`data  fig  README.md  setup.py  src`

`ls data` gives
`fndata-1.5  fndata-1.6  fndata-1.7  glove.6B.100d.framevocab.txt  glove.6B.100d.txt  neural`

`ls data/fndata-1.7` or any other version gives
```
docs   frameIndex.xml  frRelation.xml  fulltextIndex.xml  lu           luIndex.xsl  README.txt  semTypes.xml
frame  frameIndex.xsl  fulltext        fulltextIndex.xsl  luIndex.xml  miscXML      schema
```

`ls data/neural/fn1.7` gives
```
fn1.7.dev.syntaxnet.conll             fn1.7.exemplar.train.syntaxnet.conll.sents  fn1.7.test.syntaxnet.conll
fn1.7.dev.syntaxnet.conll.sents       fn1.7.fulltext.train.syntaxnet.conll        fn1.7.test.syntaxnet.conll.sents
fn1.7.exemplar.train.syntaxnet.conll  fn1.7.fulltext.train.syntaxnet.conll.sents
```

The file generation doesn't seem to be giving any error.
So far I haven't train any model. 
I just try to reuse the evaluation script providing the gold test data as input.
I would expect to get 100% performance but instead it does not seem to find the frames.

So I believe I have some frame ontology that is missing?
Buy I do not know how to generate it.

Thanks again!

**Comment by swabhs** [comment]
Hi Gabriel,

Thanks for your patience. Looks like the neural/ directory is missing under
data/? The preprocessing should result in a structure which looks like

[swabha@pin open-sesame]$ tree data/neural/
data/neural/
└── fn1.7
    ├── fn1.7.dev.syntaxnet.conll
    ├── fn1.7.dev.syntaxnet.conll.sents
    ├── fn1.7.fulltext.train.syntaxnet.conll
    ├── fn1.7.fulltext.train.syntaxnet.conll.sents
    ├── fn1.7.test.syntaxnet.conll
    └── fn1.7.test.syntaxnet.conll.sents

1 directory, 6 files


As regards to FN 1.6, the evaluation runs as expected on my end. How
exactly are you running evaluation?

**Comment by GMarzinotto** [comment]
Hello, 

I have almost the same directory settings for  `data/neural/fn1.7`
I have the **exemplar.train** files as well but that shouldn't be a problem 
As you say, I may not be running the evaluation script the right way

I do: 
`python evaluation.py ../data/neural/fn1.X/fn1.X.test.syntaxnet.conll`

or 

`python src/evaluation.py ./data/neural/fn1.X/fn1.X.test.syntaxnet.conll`

and I make sure that the `TEST_CONLL` variable is set to the right version of fn1.X

Thank you very much for your help!

**Comment by swabhs** [comment]
Hi Gabriel,

I have fixed this now, it should run as expected.
