### ISSUE TITLE
dynet problem: RuntimeError: Magnitude of gradient is bad: inf

### ISSUE THREAD

**Issue by fuzihaofzh** [swabhs/open-sesame#13]
I use:
```
python -m sesame.$MODEL --model_name sample-$MODEL --mode train
```
where MODEL=segrnn-argid. But I got:

```
Traceback (most recent call last):
  File "/gds/miniconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/gds/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/workbench/open-sesame/sesame/segrnn-argid.py", line 956, in <module>
    adam.update()
  File "_dynet.pyx", line 5728, in _dynet.Trainer.update
  File "_dynet.pyx", line 5733, in _dynet.Trainer.update
RuntimeError: Magnitude of gradient is bad: inf
```
Could anyone suggest for this problem? I wonder whether it is caused by the version of dynet?

**Comment by swabhs** [comment]
This generally happens in case of exploding / vanishing gradients late in the training - it's a DyNet error message. How far into the training do you see this? I recommend the latest version of DyNet.

**Comment by fuzihaofzh** [comment]
@swabhs I do use the latest version of DyNet. It appears at about after training it for one day.

**Comment by swabhs** [comment]
Yes, that's expected - it is probably a result of overfitting on the training data. I currently don't have a workaround for this, but some kind of learning rate scheduling might work. After certain epochs, you might want to use a lower learning rate. You might also try early stopping. However, your trained models should work as expected.
