### ISSUE TITLE
Exception: ('Rule not defined for part-of-speech word', u'wp', u'who') + Fix for it

### ISSUE THREAD

**Issue by BBCMax** [swabhs/open-sesame#14]
Hi,
I came across a bug when retraining open-sesame on FrameNet 1.7 data:
`Exception: ('Rule not defined for part-of-speech word', u'wp', u'who')`

I can see that this is fixable by adding 'wp' to the POS tag mappings in `targetid.py`, I added it to the **noun** mapping as this seems to be the best fit?

Just raising this issue in case anyone else stumbles across it, and because it can easily be fixed.

Thanks!

**Comment by swabhs** [comment]
Hi!

Yes that fix should work. I have also updated the codebase with the said fix.
