### ISSUE TITLE
Error in readme 

### ISSUE THREAD

**Issue by silentrob** [swabhs/open-sesame#19]
Running:
```
python -m sesame.targetid --mode predict --model_name pretrained-targetid --raw_input sentences.txt
```

Returns `targetid.py: error: option --mode: invalid choice: 'predict' (choose from 'convert_conll_to_fe', 'count_frame_elements', 'compare_fefiles')`

This may be env related or something else I overlooked. 
Python 2.7 / FN 1.7

**Comment by swabhs** [comment]
This has been fixed, thanks!
