### ISSUE TITLE
training question

### ISSUE THREAD

**Issue by silentrob** [swabhs/open-sesame#21]
In both tagetid and frameid testing I eventually bail out with "Ran out of patience, ending training." before I get to the end of the defined epoch. Is this a hyper hyperparameter problem and not finding a local minimum?

**Comment by swabhs** [comment]
No, it's just an early stopping mechanism - if I don't get improvements on the dev data for more than a certain number of epochs, I typically stop training. You could alternatively set the number of epochs hyperparameter to a lower value.
