### ISSUE TITLE
I can't install dynet for python27. 

### ISSUE THREAD

**Issue by mahmuthz** [swabhs/open-sesame#25]
I can't install dynet for python27. (It is ok in python 3 )
error: `make` not found, and `MAKE` is not set
do you have any suggestion for me to use the open-sesame?

**Comment by swabhs** [comment]
I'm able to install `dynet` correctly in python 2.7, what error are you getting?

**Comment by mahmuthz** [comment]
Collecting dynet
  Using cached https://files.pythonhosted.org/packages/22/8e/148ecf0ec4ffce667e84abd6aa134bbff1f73cbb99c92c198149f122889e/dyNET-2.1.tar.gz
Requirement already satisfied: cython in c:\users\admin\anaconda2\lib\site-packages (from dynet) (0.29.2)
Requirement already satisfied: numpy in c:\users\admin\anaconda2\lib\site-packages (from dynet) (1.15.4)
Building wheels for collected packages: dynet
  Running setup.py bdist_wheel for dynet: started
  Running setup.py bdist_wheel for dynet: finished with status 'error'
  Complete output from command C:\Users\Admin\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admin\\appdata\\local\\temp\\pip-install-9bqi8m\\dynet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\admin\appdata\local\temp\pip-wheel-6zwmmg --python-tag cp27:
  running bdist_wheel
  running build
  INFO:root:CMAKE_PATH='C:\\Users\\Admin\\Anaconda2\\Library\\bin\\cmake.exe'
  INFO:root:MAKE_PATH='C:\\Program Files\\Git\\bin\\make.exe'
  INFO:root:MAKE_FLAGS='-j 8'
  INFO:root:EIGEN3_INCLUDE_DIR='c:\\users\\admin\\appdata\\local\\temp\\pip-install-9bqi8m\\dynet\\build\\py2.7-64bit\\eigen'
  INFO:root:EIGEN3_DOWNLOAD_URL='https://bitbucket.org/eigen/eigen/get/b2e267dc99d4.zip'
  INFO:root:CC_PATH=None
  INFO:root:CXX_PATH=None
  INFO:root:SCRIPT_DIR='c:\\users\\admin\\appdata\\local\\temp\\pip-install-9bqi8m\\dynet'
  INFO:root:BUILD_DIR='c:\\users\\admin\\appdata\\local\\temp\\pip-install-9bqi8m\\dynet\\build\\py2.7-64bit'
  INFO:root:INSTALL_PREFIX='C:\\Users\\Admin\\Anaconda2\\Lib\\site-packages\\..\\..\\..'
  INFO:root:PYTHON='C:\\Users\\Admin\\Anaconda2\\python.exe'
  cmake version 3.9.4
  
  CMake suite maintained and supported by Kitware (kitware.com/cmake).
  error: `gcc` not found, and `CC` is not set.
  
  ----------------------------------------
  Running setup.py clean for dynet
Failed to build dynet
Installing collected packages: dynet
  Running setup.py install for dynet: started
    Running setup.py install for dynet: finished with status 'error'
    Complete output from command C:\Users\Admin\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admin\\appdata\\local\\temp\\pip-install-9bqi8m\\dynet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\admin\appdata\local\temp\pip-record-ajkj_9\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    INFO:root:CMAKE_PATH='C:\\Users\\Admin\\Anaconda2\\Library\\bin\\cmake.exe'
    INFO:root:MAKE_PATH='C:\\Program Files\\Git\\bin\\make.exe'
    INFO:root:MAKE_FLAGS='-j 8'
    INFO:root:EIGEN3_INCLUDE_DIR='c:\\users\\admin\\appdata\\local\\temp\\pip-install-9bqi8m\\dynet\\build\\py2.7-64bit\\eigen'
    INFO:root:EIGEN3_DOWNLOAD_URL='https://bitbucket.org/eigen/eigen/get/b2e267dc99d4.zip'
    INFO:root:CC_PATH=None
    INFO:root:CXX_PATH=None
    INFO:root:SCRIPT_DIR='c:\\users\\admin\\appdata\\local\\temp\\pip-install-9bqi8m\\dynet'
    INFO:root:BUILD_DIR='c:\\users\\admin\\appdata\\local\\temp\\pip-install-9bqi8m\\dynet\\build\\py2.7-64bit'
    INFO:root:INSTALL_PREFIX='C:\\Users\\Admin\\Anaconda2\\Lib\\site-packages\\..\\..\\..'
    INFO:root:PYTHON='C:\\Users\\Admin\\Anaconda2\\python.exe'
    cmake version 3.9.4
    
    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    error: `gcc` not found, and `CC` is not set.

**Comment by mahmuthz** [comment]
!

**Comment by TorhamDev** [comment]
you need to install gcc compiler
