### ISSUE TITLE
Arguments prefix

### ISSUE THREAD

**Issue by jayralencar** [swabhs/open-sesame#27]
Hi everybody. 

I am just starting to learn frame-semantic parsing, and I have a question:

Given the follow example:
```
1	she	_	She	_	PRP	4	_	_	_	_	_	_	_	S-Ingestor
2	ate	_	eat	_	VBD	4	_	_	_	_	_	eat.v	Ingestion	O
3	porridge	_	UNK	_	NN	4	_	_	_	_	_	_	_	S-Ingestibles
4	.	_	.	_	.	4	_	_	_	_	_	_	_	O
```
What means "S" before of Ingestor, for example?

PS: English is not my mother language, so excuse me if I sound odd sometimes.

Thank you.

**Comment by swabhs** [comment]
The S- tag denotes a singular argument, i.e. an argument with length = 1. In this case, the single length span "She" is the `ingestor`. Compare this with other tags such as `B-` for beginning, `I-` for inside, and `O-` for outside. Hope this helps!
