### ISSUE TITLE
Clarify required DyNet version

### ISSUE THREAD

**Issue by danielhers** [swabhs/open-sesame#3]
The README says `DyNet-v2`, but using 2.0 (from pip) fails:

    AttributeError: '_dynet.ParameterCollection' object has no attribute 'load'

Also, 2.0 doesn't require Boost.
Is it actually 1.1?

**Comment by CogMachines** [comment]
It is using 1.1.  Changes to support 2.0 are pretty minimal.  I'll add a pull request once I verify the decay rate changes are working.

**Comment by swabhs** [comment]
README is now updated with the correct version of DyNet (2.0) and the codebase is updated accordingly.
