### ISSUE TITLE
Add python 3.X compatibility

### ISSUE THREAD

**Issue by brenowca** [swabhs/open-sesame#32]
Code compatibility with python 3 would be a nice feature since python 2.7 is no longer continued.

**Comment by brenowca** [comment]
I made a pull request, #33, and I believe that it would close this issue and provide python 2.7 and 3.X compatibility to this repository.

**Comment by wanicca** [comment]
```
Reading model from logs/fn1.7-pretrained-targetid/best-targetid-1.7-model ...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wanicca/code/framebase/open-sesame/sesame/targetid.py", line 430, in <module>
    model.populate(model_file_name)
  File "_dynet.pyx", line 1461, in _dynet.ParameterCollection.populate
  File "_dynet.pyx", line 1516, in _dynet.ParameterCollection.populate_from_textfile
RuntimeError: Dimensions of lookup parameter /_0 lookup up from file ({100,400574}) do not match parameters to be populated ({100,400000})
```

I tried the pretrained model with your code, but there is something buggy...

**Comment by Merbom** [comment]
I have the same problem...

**Comment by brenowca** [comment]
Hi Wanicca,

Sorry for the delay in the reply. I had a very busy November. Basically
what I found is that there was some inconsistency in the original version
of the code for dealing with 'utf-8' strings and binary strings. This is a
known difficulty with Python 2.7, that Python 3.7 overcome. As far as I
could understand, this situation leads to a shifty bug that made a sub-set
of the strings in the vocabulary to be counted twice. That bug led to a
vocabulary slightly bigger than the expected one (with two repeated words
represented in binary and unicode).

Anyways, I have trained the models again. I have made some more changes (on
the encoding /decoding stuff)  and will make a commit soon.

After I make this new commit, I ask if you and *@swabhs *could kindly take
some time to scrutinize the code and make sure that everything is making
sense. After that, we can all validate if the vocabulary encoding issue is
correct and the results are what you would expect.


Thank you for your time and for spotting the problem.

Breno

**Comment by eahogue** [comment]
This would seem like a very important thing to fix because, as far as I can tell, NLTK relies on Python 3 and Open-Sesame relies on NLTK. Until this is resolved, is there any way to get around this problem?

To be clear, I can easily install NLTK for python 3 but not python 2. When I try running the sesame.preprocessor script with python 3, however, there is a cascade of bugs. When I fix one, another bug pops up.

Is there an interim fix for this? Thank you!

**Comment by free-soellingeraj** [comment]
I have a branch running to resolve these issues.  I have made it through training for the first 2 networks, and getting the 3rd now.  On Python 3.6.X.  Next, I will put it in a docker container.

dev branch with the latest: https://github.com/free-soellingeraj/open-sesame/tree/soellingeraj/python36-updates

I will push to master once I have gone through each model and start a new branch for the dockerfile.

**Comment by free-soellingeraj** [comment]
Here's a working version using Python3.6 and the option for GPU compute.
https://github.com/free-soellingeraj/open-sesame

**Comment by avijit-thawani** [comment]
I struggled with the exact versions of libraries needed for running this 2.7 original version of open-sesame, so I'm sharing here what worked for me:
`pip2 install numpy==1.15.0 dynet nltk==3.4`
The remaining instructions, eg. downloading nltk modules, can run as usual.

**Comment by swabhs** [comment]
Thanks everyone for the discussion above. I've now switched to Python 3.7, and hope this resolves most of the issues above. Special thanks to @BrenoWSRCa and @free-soellingeraj  for creating forks with this compatibility!
