### ISSUE TITLE
annotation hack, framenet, glove and dynet

### ISSUE THREAD

**Issue by kleinias** [swabhs/open-sesame#5]
Hi, I tried to try it out, but I failed. 
First, the preprocess script broke, because that "annotation_id" was not defined, despite I don't think, that it wasn't defined, but that was the error. So I deleted the hack and it worked.

Second, I tried it with the newest version of FrameNet, 1.7, and it failed, somehow looking for version 1.5., which was obviosly not there. So I tried version 1.5. and I got it.

Then I tried to train the parser, but it looked automatically for the glove vectors in the data directory, which weren't there (although I didn't tell it, to use any glove). After I put the files there, it did as it should

But now it complains:
AttributeError: '_dynet.ParameterCollection' object has no attribute 'load'

I installed DyNet version 2. Hope that this is right. Can't see anything else, but the Model() and .load() calls seems to be deprecated. I tried to change it to dynet.ParamCollection() and .populate(), but then it couldn't read the model: "RuntimeError: Could not read model from model.frameid.1.5"

**Comment by eyb1** [comment]
Just a comment regarding the FrameNet version issue, did you change line 20 in ```src\globalconfig.py``` from ```VERSION="1.5"``` to ```VERSION="1.7"```?

**Comment by BBCMax** [comment]
Hi, I am having similar issues.

I also didn't realise that the FrameNet version could be changed in `src\globalconfig.py`, which fixed one issue for me.

 In `src\globalconfig.py` should `FILTERED_WVECS_FILE` refer to the file `glove.6B.100d.framevocab.txt` created in the tutorial? In your code it is set to `glove.6B.100d.framenet.txt`, however I don't see any other references to this file...

Working with my assumption above, I subsequently get a DyNet error too:

> RuntimeError: Could not read model from model.frameid.1.7

Any advice would be much appreciated!
Thanks

**Comment by swabhs** [comment]
Fixed the name of the filtered embeddings file now.

The RunTimeError might be occurring because no model was saved.
