### ISSUE TITLE
Magnitude of gradient is bad: inf

### ISSUE THREAD

**Issue by hahmyg** [swabhs/open-sesame#9]
Now I am trying to train 'Arg Identification' using the code "segrnn-argid.py"

When I trained 'target identification' using the code "frameid.py", 
Everything is ok.

However, "segrnn-argid.py" code returns an error:

`RuntimeError: Magnitude of gradient is bad: inf`

How can I handle it?

**Comment by hahmyg** [comment]
In additionally, I used 'FrameNet 1.7' data which is preprocessed by open-sesame itself

**Comment by swabhs** [comment]
This is an exception thrown by DyNet - it probably means the model is overfitting. I would suggest using a lower learning rate.
